//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace InfosinOpenAuthDB.Repository.Mapping
{
    public partial class SysFormQINGJIAMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<InfosinOpenAuthDB.Repository.Domain.SysFormQINGJIA>
    {
        public SysFormQINGJIAMap()
        {
            // table
            ToTable("Sys_Form_QINGJIA", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Data1)
                .HasColumnName("data_1")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Data2)
                .HasColumnName("data_2")
                .HasMaxLength(255)
                .IsOptional();

            // Relationships
        }
    }
}
