//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace InfosinOpenAuthDB.Repository.Mapping
{
    public partial class SysFlowSchemeMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<InfosinOpenAuthDB.Repository.Domain.SysFlowScheme>
    {
        public SysFlowSchemeMap()
        {
            // table
            ToTable("Sys_FlowScheme", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.SchemeCode)
                .HasColumnName("SchemeCode")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.SchemeName)
                .HasColumnName("SchemeName")
                .HasMaxLength(200)
                .IsOptional();
            Property(t => t.SchemeType)
                .HasColumnName("SchemeType")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.SchemeVersion)
                .HasColumnName("SchemeVersion")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.SchemeCanSysUser)
                .HasColumnName("SchemeCanSys_User")
                .IsOptional();
            Property(t => t.SchemeContent)
                .HasColumnName("SchemeContent")
                .IsOptional();
            Property(t => t.FrmId)
                .HasColumnName("FrmId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FrmType)
                .HasColumnName("FrmType")
                .IsRequired();
            Property(t => t.AuthorizeType)
                .HasColumnName("AuthorizeType")
                .IsRequired();
            Property(t => t.SortCode)
                .HasColumnName("SortCode")
                .IsRequired();
            Property(t => t.DeleteMark)
                .HasColumnName("DeleteMark")
                .IsRequired();
            Property(t => t.Disabled)
                .HasColumnName("Disabled")
                .IsRequired();
            Property(t => t.Description)
                .HasColumnName("Description")
                .HasMaxLength(200)
                .IsOptional();
            Property(t => t.CreateDate)
                .HasColumnName("CreateDate")
                .IsRequired();
            Property(t => t.CreateSysUserId)
                .HasColumnName("CreateSys_UserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.CreateSysUserName)
                .HasColumnName("CreateSys_UserName")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ModifyDate)
                .HasColumnName("ModifyDate")
                .IsOptional();
            Property(t => t.ModifySysUserId)
                .HasColumnName("ModifySys_UserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ModifySysUserName)
                .HasColumnName("ModifySys_UserName")
                .HasMaxLength(50)
                .IsOptional();

            // Relationships
        }
    }
}
