//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace InfosinOpenAuthDB.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SysFormQINGJIA : Entity
    {
        public SysFormQINGJIA()
        {
          this.Data1= string.Empty;
          this.Data2= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string Data1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data2 { get; set; }

    }
}