//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Collections.Generic;
using InfosinOpenAuthDB.Repository.Domain;
using InfosinOpenAuthDB.Repository.Mapping;

namespace InfosinOpenAuthDB.Repository
{
    public partial class InfosinOpenAuthDBContext: DbContext
    {
        static  InfosinOpenAuthDBContext()
        {
            Database.SetInitializer< InfosinOpenAuthDBContext>(null);
        }
        public InfosinOpenAuthDBContext()
            :base("Name=InfosinOpenAuthDBContext")
        { }

        public InfosinOpenAuthDBContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        { }

        public System.Data.Entity.DbSet<SysApplication> SysApplications { get; set; }
        public System.Data.Entity.DbSet<SysCategory> SysCategories { get; set; }
        public System.Data.Entity.DbSet<SysCategoryType> SysCategoryTypes { get; set; }
        public System.Data.Entity.DbSet<SysFlowInstance> SysFlowInstances { get; set; }
        public System.Data.Entity.DbSet<SysFlowInstanceOperationHistory> SysFlowInstanceOperationHistories { get; set; }
        public System.Data.Entity.DbSet<SysFlowInstanceTransitionHistory> SysFlowInstanceTransitionHistories { get; set; }
        public System.Data.Entity.DbSet<SysFlowScheme> SysFlowSchemes { get; set; }
        public System.Data.Entity.DbSet<SysForm> SysForms { get; set; }
        public System.Data.Entity.DbSet<SysFormQINGJIA> SysFormQINGJIAs { get; set; }
        public System.Data.Entity.DbSet<SysModule> SysModules { get; set; }
        public System.Data.Entity.DbSet<SysModuleElement> SysModuleElements { get; set; }
        public System.Data.Entity.DbSet<SysOrg> SysOrgs { get; set; }
        public System.Data.Entity.DbSet<SysRelevance> SysRelevances { get; set; }
        public System.Data.Entity.DbSet<SysResource> SysResources { get; set; }
        public System.Data.Entity.DbSet<SysRole> SysRoles { get; set; }
        public System.Data.Entity.DbSet<SysStock> SysStocks { get; set; }
        public System.Data.Entity.DbSet<SysUser> SysUsers { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new SysApplicationMap());
            modelBuilder.Configurations.Add(new SysCategoryMap());
            modelBuilder.Configurations.Add(new SysCategoryTypeMap());
            modelBuilder.Configurations.Add(new SysFlowInstanceMap());
            modelBuilder.Configurations.Add(new SysFlowInstanceOperationHistoryMap());
            modelBuilder.Configurations.Add(new SysFlowInstanceTransitionHistoryMap());
            modelBuilder.Configurations.Add(new SysFlowSchemeMap());
            modelBuilder.Configurations.Add(new SysFormMap());
            modelBuilder.Configurations.Add(new SysFormQINGJIAMap());
            modelBuilder.Configurations.Add(new SysModuleMap());
            modelBuilder.Configurations.Add(new SysModuleElementMap());
            modelBuilder.Configurations.Add(new SysOrgMap());
            modelBuilder.Configurations.Add(new SysRelevanceMap());
            modelBuilder.Configurations.Add(new SysResourceMap());
            modelBuilder.Configurations.Add(new SysRoleMap());
            modelBuilder.Configurations.Add(new SysStockMap());
            modelBuilder.Configurations.Add(new SysUserMap());

           // InitializeMapping(modelBuilder);
        }
    }
}